export const COMPANY_LIST_BYNUMBER_REQUEST = 'COMPANY_LIST_BYNUMBER_REQUEST'
export const COMPANY_LIST_BYNUMBER_SUCCESS = 'COMPANY_LIST_BYNUMBER_SUCCESS'
export const COMPANY_LIST_BYNUMBER_FAIL = 'COMPANY_LIST_BYNUMBER_FAIL'

export const COMPANY_LIST_RESTRICT_REQUEST = 'COMPANY_LIST_RESTRICT_REQUEST'
export const COMPANY_LIST_RESTRICT_SUCCESS = 'COMPANY_LIST_RESTRICT_SUCCESS'
export const COMPANY_LIST_RESTRICT_FAIL = 'COMPANY_LIST_RESTRICT_FAIL'