# Generated by Django 3.2.6 on 2021-08-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=100)),
                ('business_number', models.CharField(max_length=100)),
                ('restricted', models.CharField(max_length=10)),
            ],
        ),
    ]
